base:
  project: "Diabetes prediction"
  target_col: "Outcome"
  random_state: 42

data_source:
  dataset: "dataset/kaggle_diabetes.csv"

load_data:
  dataset: "data/raw/kaggle_diabetes.csv"

split_data:
  train_path_X: data/processed/X_train.csv
  test_path_X: data/processed/X_test.csv
  train_path_y: data/processed/y_train.csv
  test_path_y: data/processed/y_test.csv
  test_size: 0.2