base:
  project: "Diabetes prediction"
  target_col: "Outcome"
  random_state: 42

data_source:
  dataset: "dataset/kaggle_diabetes.csv"

load_data:
  dataset: "data/raw/kaggle_diabetes.csv"

split_data:
  train_path_X: data/processed/X_train.csv
  test_path_X: data/processed/X_test.csv
  train_path_y: data/processed/y_train.csv
  test_path_y: data/processed/y_test.csv
  test_size: 0.2

transform_data:
  X_train_transform: data/transform/X_train_transform.csv
  X_test_transform: data/transform/X_test_transform.csv

ANN:
  activation: "relu"
  loss: "binary_crossentropy"
  optimizer: 'adam'
  kernel_initializer: 'uniform'
  metrics: 'accuracy'
  epochs: 200
  batch_size: 32
  input_dim: 8
  sig_act: 'sigmoid'

model_save:
  model_dir: "saved_models/ann_model.h5"