base:
  project: "Diabetes prediction"
  target_col: "Outcome"
  random_state: 42

data_source:
  dataset: "dataset/kaggle_diabetes.csv"

load_data:
  dataset: "data/raw/kaggle_diabetes.csv"

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.2